#!/usr/bin/env bash
set -e

: "${VERSION:?VERSION must be set}"
: "${SCRIPT_DIR:?SCRIPT_DIR must be set}"

WINDOWS_SCRIPT_DIR=$(echo ${SCRIPT_DIR} | tr / \\)

cat << EOF
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{29B33B35-BAD1-46A5-B07E-E52F57E5F046}
AppName=Plus-F
AppVersion=${VERSION}
;AppVerName=Plus-F ${VERSION}
AppPublisher=socialthingy.com
AppPublisherURL=http://plus-f.socialthingy.com/
AppSupportURL=http://plus-f.socialthingy.com/
AppUpdatesURL=http://plus-f.socialthingy.com/
DefaultDirName={pf}\Plus-F
DisableProgramGroupPage=yes
OutputBaseFilename=Plus-F-Install
OutputDir=Z:${WINDOWS_SCRIPT_DIR}\build\distributions\windows
Compression=lzma
SolidCompression=yes
SetupIconFile=Z:${WINDOWS_SCRIPT_DIR}\package\windows\Plus-F.ico
WizardSmallImageFile=Z:${WINDOWS_SCRIPT_DIR}\package\windows\Plus-F-setup-icon.bmp

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "Z:${WINDOWS_SCRIPT_DIR}\build\distributions\windows\Plus-F.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:${WINDOWS_SCRIPT_DIR}\build\distributions\windows\jre-10.0.2\*"; DestDir: "{app}\jre-10.0.2"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\Plus-F"; Filename: "{app}\Plus-F.exe"; IconFilename: "Z:${WINDOWS_SCRIPT_DIR}\package\windows\Plus-F.ico"
Name: "{commondesktop}\Plus-F"; Filename: "{app}\Plus-F.exe"; IconFilename: "Z:${WINDOWS_SCRIPT_DIR}\package\windows\Plus-F"; Tasks: desktopicon

[Run]
Filename: "{app}\Plus-F.exe"; Description: "{cm:LaunchProgram,Plus-F}"; Flags: nowait postinstall skipifsilent

EOF
